blog/urls.py
from django.conf.urls import url
from . import views

# 命名空间
app_name = 'blog'
urlpatterns = [
    # 匹配 imzack.me/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # 匹配 imzack.me/post/<file>/
    url(r'^post/(?P<file>[0-9a-z-]+).html$', views.PostView.as_view(), name='detail'),
    # 匹配 imzack.me/about.html
    url(r'^about.html$', views.about, name='about'),
]

comments/urls.py
from django.conf.urls import url
from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

imzack_me/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.views import forbidden, page_not_found, internal_server_error

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
]

handler403 = forbidden

handler404 = page_not_found

handler500 = internal_server_error

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.timezone import now


# 文章类
class Post(models.Model):

    # 标题，存储较短的字符串使用 CharField，设定最长为 50
    title = models.CharField('标题', max_length=50)

    # 摘要
    excerpt = models.TextField('摘要')

    # 正文，使用 TextField 来存储大段文本
    content = models.TextField('正文')

    # 日期
    date = models.DateField('日期', default=now)

    # 文件名
    file = models.CharField('文件', max_length=50)

    # 解释器显示的数据为此函数的返回值
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'file': self.file})

    class Meta:
        # 管理页面显示的中文名
        verbose_name = '文章'
        # 管理页面显示的复数中文名，不设置的话会加 s
        verbose_name_plural = '文章'
        # 日期逆序（-）排列
        ordering = ['-date']

blog/views.py
import markdown
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from comments.forms import CommentForm
from .models import Post


class IndexView(ListView):
    # 要获取的模型
    model = Post
    # 指定视图渲染的模板
    template_name = 'blog/index.html'
    # 指定获取的模型列表数据保存的变量名，此变量会被传递给模板
    context_object_name = 'post_list'
    # 指定每一页包含的文章数量
    paginate_by = 5

    def get_queryset(self):
        post_list = super(IndexView, self).get_queryset()
        for post in post_list:
            # 对摘要进行基础 Markdown 渲染
            post.excerpt = markdown.markdown(post.excerpt)
        return post_list

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)

        # 获取父类生成的字典的模板变量
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        pagination_data = self.pagination_data(paginator, page, is_paginated)

        context.update(pagination_data)

        return context

    # 获取显示分页导航条需要的数据
    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            # 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
            return {}

        # 当前页左边连续的页码号，初始值为空
        left = []

        # 当前页右边连续的页码号，初始值为空
        right = []

        # 标示第 1 页页码后是否需要显示省略号
        left_has_more = False

        # 标示最后一页页码前是否需要显示省略号
        right_has_more = False

        # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
        first = False

        # 标示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
        last = False

        # 获得用户当前请求的页码号
        page_number = page.number

        # 获得分页后的总页数
        total_pages = paginator.num_pages

        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        page_range = paginator.page_range

        if page_number == 1:
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            right = page_range[page_number:page_number + 2]

            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
            if right[-1] < total_pages - 1:
                right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
            # 此时只要获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
            if left[0] > 2:
                left_has_more = True

            # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
            # 所以需要显示第一页的页码号，通过 first 来指示
            if left[0] > 1:
                first = True
        else:
            # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data


class PostView(DetailView):
    model = Post
    template_name = 'blog/post.html'
    context_object_name = 'post'
    # 指定 URL 中模板的参数
    slug_url_kwarg = 'file'
    # 指定 Post 中哪个字段对应 URL 中模板的参数
    slug_field = 'file'

    def get_object(self, queryset=None):
        # 对 content 进行 Markdown 渲染
        post = super(PostView, self).get_object(queryset=None)
        post.content = markdown.markdown(post.content,
                                         extensions=[
                                             'markdown.extensions.extra',
                                             # 语法高亮
                                             'markdown.extensions.codehilite',
                                         ])
        return post

    def get_context_data(self, **kwargs):
        # 将评论列表和表单传递给模板
        context = super(PostView, self).get_context_data(**kwargs)
        form = CommentForm()
        # 获取这篇 post 下的全部评论
        comment_list = self.object.comment_set.all()
        context.update({'form': form, 'comment_list': comment_list, 'enable_comments': False})
        return context


def about(request):
    return render(request, 'blog/about.html')


def forbidden(request):
    return render(request, 'status/403.html')


def page_not_found(request):
    return render(request, 'status/404.html')


def internal_server_error(request):
    return render(request, 'status/500.html')

templates/blog/about.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}关于 | 全杰是也{% endblock title %}

{% block main %}
    <article class="about">
        <div class="about-title">关于</div>
        <div class="about-content">
            <div class="about-section-title">网站</div>
            <div>
                <span>本网站托管于</span>
                <a href="https://www.vultr.com"><img src="{% static 'blog/img/vultr.svg' %}" class="vultr" alt="Vultr"></a>
                <span>洛杉矶机房，由</span>
                <a href="https://www.djangoproject.com"><img src="{% static 'blog/img/django.svg' %}" class="django" alt="Django"></a>
                <span>强力驱动。</span>
            </div>
            <div class="about-section-title">推广</div>
            <div>如果你也想购买 Vultr 的 VPS，欢迎使用我的<a href="https://www.vultr.com/?ref=7260027" class="underline">推荐链接</a>。</div>
        </div>
    </article>
{% endblock main %}

templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
    <article class="post">
        <header>
            <div class="post-title">{{ post.title }}</div>
            <div class="post-time post-time-detail">
                <time datetime="{{ post.time|date:"Y-m-d" }}">{{ post.time|date:"Y-m-d" }}</time>
            </div>
{#            <div class="widget widget-content">#}
{#                <h3 class="widget-title">文章目录</h3>#}
{#                {{ post.toc|safe }}#}
{#            </div>#}
        </header>
        <div class="post-content">
            {{ post.content|safe }}
        </div>
    </article>
    <hr>
    <section class="comment">
        <div class="comment-list-title"><span>{{ comment_list.count }}</span> 条评论</div>
        <ul class="comment-list list-unstyled">
            {% for comment in comment_list %}
            <li class="comment-item">
                <span class="comment-name">
                    {% if comment.website %}
                    <a href="{{ comment.website }}">
                    {% endif %}
                    {{ comment.name }}
                    {% if comment.website %}
                    </a>
                    {% endif %}
                </span>
                <time class="comment-time" datetime="{{ comment.time|date:"Y-m-d H:i" }}">{{ comment.time|date:"Y-m-d H:i" }}</time>
                <div class="comment-content">
                    {{ comment.content }}
                </div>
            </li>
            {% empty %}
            暂无评论
            {% endfor %}
        </ul>
        <div class="comment-form-title">发表评论</div>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    <!-- 自动渲染成表单控件 -->
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="col-md-6">
                    <label for="{{ form.website.id_for_label }}">网站（可选）：</label>
                    {{ form.website }}
                    {{ form.website.errors }}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.content.id_for_label }}">评论：</label>
                    {{ form.content }}
                    {{ form.content.errors }}
                    <button type="submit" class="comment-submit-button">提交</button>
                </div>
            </div>
        </form>
    </section>
{% endblock main %}

templates/blog/index.html
{% extends 'base.html' %}

{% block title %}全杰是也{% endblock title %}

{% block main %}
    {% for post in post_list %}
        <article class="post">
            <header>
                <div class="post-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </div>
                <div class="post-time">
                    <time datetime="{{ post.date|date:"Y-m-d" }}">{{ post.date|date:"Y-m-d" }}</time>
                </div>
            </header>
            <div class="post-excerpt">
                <p>{{ post.excerpt|safe }}</p>
            </div>
        </article>
    {% endfor %}

    {% if is_paginated %}
        <div class="pagination">
            {% if first %}
                <a href="?page=1">1</a>
            {% endif %}
            {% if left %}
                {% if left_has_more %}
                    <span>...</span>
                {% endif %}
                {% for i in left %}
                    <a href="?page={{ i }}">{{ i }}</a>
                {% endfor %}
            {% endif %}
            <span class="current-page"><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></span>
            {% if right %}
                {% for i in right %}
                    <a href="?page={{ i }}">{{ i }}</a>
                {% endfor %}
                {% if right_has_more %}
                    <span>...</span>
                {% endif %}
            {% endif %}
            {% if last %}
                <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
            {% endif %}
        </div>
    {% endif %}
{% endblock main %}

templates/blog/post.html
{% extends 'base.html' %}

{% block title %}{{ post.title }} | 全杰是也{% endblock title %}

{% block main %}
    <article class="post">
        <header>
            <div class="post-title">{{ post.title }}</div>
            <div class="post-time">
                <time datetime="{{ post.date|date:"Y-m-d" }}">{{ post.date|date:"Y-m-d" }}</time>
            </div>
        </header>
        <div class="post-content">
            {{ post.content|safe }}
        </div>
    </article>
    {% if enable_comments %}
    <hr>
    <section class="comment">
        {% if comment_list.count > 0 %}
        <div class="comment-list-title">评论列表</div>
        <ul class="comment-list list-unstyled">
            {% for comment in comment_list %}
            <li class="comment-item">
                <span class="comment-name">
                    {% if comment.website %}
                    <a href="{{ comment.website }}">
                    {% endif %}
                    {{ comment.name }}
                    {% if comment.website %}
                    </a>
                    {% endif %}
                </span>
                <time class="comment-time" datetime="{{ comment.time|date:"Y-m-d H:i" }}">{{ comment.time|date:"Y-m-d H:i" }}</time>
                <div class="comment-content">
                    {{ comment.content }}
                </div>
            </li>
            {% endfor %}
        </ul>
        {% endif %}
        <div class="comment-form-title">发表评论</div>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="col-md-6">
                    <label for="{{ form.website.id_for_label }}">网站（可选）：</label>
                    {{ form.website }}
                    {{ form.website.errors }}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.content.id_for_label }}">评论：</label>
                    {{ form.content }}
                    {{ form.content.errors }}
                    <button type="submit" class="comment-submit-button">提交</button>
                </div>
            </div>
        </form>
    </section>
    {% endif %}
{% endblock main %}