blog/urls.py
from django.conf.urls import url
from . import views

# 命名空间
app_name = 'blog'
urlpatterns = [
    # 匹配 imzack.me/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # 匹配 imzack.me/post/<file>/
    url(r'^post/(?P<file>[0-9a-z-]+).html$', views.PostView.as_view(), name='detail'),
    # 匹配 imzack.me/about.html
    url(r'^about.html$', views.about, name='about'),
]

imzack_me/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.views import forbidden, page_not_found, internal_server_error

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
]

handler403 = forbidden

handler404 = page_not_found

handler500 = internal_server_error

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock title %}</title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" href="{% static "blog/img/favicon.ico" %}" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.3/css/all.css">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
<header class="header">
    <div class="container">
        <div class="row no-gutter">
            <div class="col-md-5 col-md-offset-2 col-sm-10 col-xs-8">
                <div class="header-title">
                    <a href="{% url 'blog:index' %}">全杰是也</a>
                </div>
            </div>
            <div class="col-md-1 col-md-offset-2 col-sm-2 col-xs-4">
                <div class="header-menu-icon-bar">
                    <div class="header-menu-icon">
                        <a href="{% url 'blog:about' %}"><span class="fas fa-user"></span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="content">
    <div class="container">
        <div class="row">
            <main class="col-md-8 col-md-offset-2">
                {% block main %}
                {% endblock main %}
            </main>
        </div>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017-2018 全杰是也</p>
            </div>
        </div>
    </div>
</footer>

</body>
</html>